#!/bin/bash
# AF-10: install-hooks.sh — install pre-commit git hooks for architecture fitness tests
# Copies all fitness test scripts to .git/hooks/ as pre-commit

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

echo "AF-10: Installing pre-commit hooks for architecture fitness tests..."

cd "$REPO_ROOT"

# Ensure hooks directory exists
mkdir -p "$HOOKS_DIR"

# Create the pre-commit hook that runs all fitness tests
cat > "$HOOKS_DIR/pre-commit" << 'PRECOMMIT_EOF'
#!/bin/bash
# Pre-commit hook: run architecture fitness tests
# Auto-generated by arch-fitness/install-hooks.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)/scripts/arch-fitness"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"

echo "Running architecture fitness tests..."

# Source and run each test
for test in "$SCRIPT_DIR"/no-*.sh; do
  if [ -f "$test" ] && [ "$(basename "$test")" != "install-hooks.sh" ]; then
    name=$(basename "$test" .sh)
    echo ""
    echo "=== $name ==="
    if ! bash "$test"; then
      echo ""
      echo "ARCHITECTURE FITNESS TEST FAILED: $name"
      echo "Please fix the issue before committing. Run 'bash scripts/arch-fitness/$name.sh' for details."
      exit 1
    fi
  fi
done

echo ""
echo "All architecture fitness tests passed!"
PRECOMMIT_EOF

chmod +x "$HOOKS_DIR/pre-commit"

# Also copy individual test scripts for manual running
for script in "$SCRIPT_DIR"/*.sh; do
  if [ -f "$script" ] && [ "$(basename "$script")" != "install-hooks.sh" ]; then
    cp "$script" "$HOOKS_DIR/"
    chmod +x "$HOOKS_DIR/$(basename "$script")"
  fi
done

echo "Pre-commit hooks installed successfully."
echo ""
echo "The following hooks are now active:"
ls -1 "$HOOKS_DIR"/no-*.sh 2>/dev/null | xargs -I{} basename {} | sed 's/^/  - /'
echo ""
echo "To update hooks after changes, run: bash scripts/arch-fitness/install-hooks.sh"
